/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vfernand' at '1/20/17 8:45 PM' with Gradle 3.2.1
 *
 * @author vfernand, @date 1/20/17 8:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
